schedule: 'schedule.json'
indir: 'extractions_STR'
partition_col: 'sru'
min_partition: 1
max_spacer: 8
max_partition: 10
min_sequence_length: 10
min_consensus_repeats: 3
min_arm_length: 10
pattern: 'STR'
seq_col: 'sequence'
step_threshold: 0.05
assembly_summary: 'data/assembly_summary_with_tree.csv.gz'
